# This code creates a variety of files with different extensions and names for testing purposes.
open("notes.txt", "w").close()
open("report.pdf","w").close()
open("presentation.pptx","w").close()
open("README.md","w").close()
open("photo.jpg","w").close()
open("screenshot.PNG","w").close()
open("diagram.svg","w").close()
open("backup.zip","w").close()
open("archive.tar.gz","w").close()
open("files.rar","w").close()
open("installer.exe","w").close()
open("setup.msi","w").close()
open("script.sh","w").close()
open("video.mp4","w").close()
open("song.mp3","w").close()
open("UPPERCASE.PDF","w").close()
open("nonextension", "w").close()
open("weird.FILE", "w").close()
